docsDir: docs
# entryPoint: docs/features.md
ignore:
  - "**/node_modules/**"
  - "**/dist/**"
layout: reader
docOrder:
  - features.md
  - design-decisions.md
  - use-cases.md
  - implementation.md
  - research.md
docOrderStrict: true
